### ISSUE TITLE
request to handle preorder traversal on empty tree

### ISSUE THREAD

**Issue by mindheist** [RunestoneInteractive/pythonds#6]
pre-order traversal code currently looks like this in the book . In-order and post-order traversals handle the case where the tree might be empty , but not pre-order. Would be nice to add a check here.

` def preorder(self):
    print(self.key)
    if self.leftChild:
        self.leftChild.preorder()
    if self.rightChild:
        self.rightChild.preorder()`

Listing 3 on this page : http://interactivepython.org/runestone/static/pythonds/Trees/TreeTraversals.html

**Comment by bnmnetp** [comment]
Sorry, but since this is a method of a BinaryTree instance,  there has to be an instance of the tree in order to call the method in the first place.   ``myTree.preorder() ``  This is different from listing 2 where the tree is passed as a parameter  ``preorder(myTree)``  In the first case if myTree is None then you will get an error "NoneType object has no method preorder"
